### ISSUE TITLE
SNES_MiSTer is skipped.

### ISSUE THREAD

**Issue by joshuacant** [MiSTer-devel/MiSTer-bootstrap#6]
The SNES core isn't being downloaded by the current release, and I'm not entirely sure why. There's a releases folder, and the files end in .rbf so it seems like it should work? But it doesn't get downloaded when running it. Sorry I can't provide any more useful information.

**Comment by w00tazn** [comment]
The GitHub client used by the go program appears to only return 64 repositories and not all 102 that are included under the org.

Wonder if there's a setting that keeps it from getting returned by the GitHub client.

**Comment by w00tazn** [comment]
Seems like this was fixed in the latest update that switched it from using the go github client to a json parser.

**Comment by joshuacant** [comment]
Fixed in alpha 2.
